baseURL = 'https://tyfr.org/'
languageCode = 'en-us'
defaultContentLanguage = "en-us"
enableEmoji = true
title = 'Tymoteusz Frankiewicz - The homebase'

# traditional way: theme component resides in directory 'themes'
theme = "hugo-blog-template"

############################## English language ################################
[Languages.en-us]
  languageName = "English"
  languageCode = "en-us"
  contentDir = "content/en"
  weight = 1

  [Languages.en-us.menu]
  [[Languages.en-us.menu.main]]
    # The page reference (pageRef) is useful for menu highlighting
    # When pageRef is set, setting `url` is optional; it will be used as a fallback if the page is not found.
    pageRef="/"
    name = 'Home'
    url = '/'
    weight = 10
  [[Languages.en-us.menu.main]]
    pageRef="about"
    name = 'About'
    url = '/pages/about/'
    weight = 20
  [[Languages.en-us.menu.main]]
    pageRef="resume"
    name = 'Résumé'
    url = '/pages/resume/'
    weight = 30

[Languages.en-us.params]
  sitename = "Tymoteusz Frankiewicz - The homebase"
  defaultColor = "auto" # set color mode: dark, light, auto
  description = "Tymoteusz Frankiewicz, Software Engineer"
  mainSections = ['/']
  toc = true # set to false to disable table of contents 'globally'
  tocOpen = false # set to true to open table of contents by default
  goToTop = true # set to false to disable 'go to top' button
  dateFormat = "" # date format used to show dates on various pages. If nothing is specified, then "2 Jan 2006" format is used.

[Languages.en-us.params.author]
  avatar = "avatar.png"
  intro = "Tymoteusz Frankiewicz, Software Engineer"
  name = "Tymoteusz Frankiewicz"
  description = "Fullstack Software Engineer with experise in Python, Java and Javascript web developement. A proud member of Infoguard DevOps team."

# Allow to override webmanifest options
[Languages.en-us.params.webmanifest]
  name = "sitename" # will use "params.sitename" or "title" by default
  short_name = "sitename" # same as name
  start_url = "/" # will use homepage url by default
  theme_color = "#434648" # default is "#434648" (base color of text). Also will override html `<meta name="theme-color" />`
  background_color = "#fff" # by default depend on "params.defaultColor" for "light" or "auto" will be set to "#fff" for dark will be "#131418" (color of dark mode background)
  display = "standalone"

############################## German language ################################
[Languages.de-ch]
  languageName = "German"
  languageCode = "de-ch"
  contentDir = "content/de"
  weight = 1

  [Languages.de-ch.menu]
  [[Languages.de-ch.menu.main]]
    # The page reference (pageRef) is useful for menu highlighting
    # When pageRef is set, setting `url` is optional; it will be used as a fallback if the page is not found.
    pageRef="/"
    name = 'Startseite'
    url = '/'
    weight = 10
  [[Languages.de-ch.menu.main]]
    pageRef="about"
    name = 'Über mich'
    url = '/pages/about/'
    weight = 20
  [[Languages.de-ch.menu.main]]
    pageRef="resume"
    name = 'Résumé'
    url = '/pages/resume/'
    weight = 30
  
[Languages.de-ch.params]
  sitename = "Tymoteusz Frankiewicz - The homebase"
  defaultColor = "auto" # set color mode: dark, light, auto
  description = "Tymoteusz Frankiewicz, Software Enginieur"
  mainSections = ['/']
  toc = true # set to false to disable table of contents 'globally'
  tocOpen = false # set to true to open table of contents by default
  goToTop = true # set to false to disable 'go to top' button
  dateFormat = "" # date format used to show dates on various pages. If nothing is specified, then "2 Jan 2006" format is used.


[Languages.de-ch.params.author]
  avatar = "avatar.png"
  intro = "Tymoteusz Frankiewicz, Software Enginieur"
  name = "Tymoteusz Frankiewicz"
  description = "Fullstack Software Engineer mit Expertise in Python, Java und Javascript Webentwicklung. Stolzer Mitglied des Infoguard DevOps Teams."

  # Allow to override webmanifest options
  [Languages.de-ch.params.webmanifest]
    name = "sitename" # will use "params.sitename" or "title" by default
    short_name = "sitename" # same as name
    start_url = "/" # will use homepage url by default
    theme_color = "#434648" # default is "#434648" (base color of text). Also will override html `<meta name="theme-color" />`
    background_color = "#fff" # by default depend on "params.defaultColor" for "light" or "auto" will be set to "#fff" for dark will be "#131418" (color of dark mode background)
    display = "standalone"

###################################################################

# Allow to override `browserconfig.xml` params (configuration for windows embedded browsers)
[params.browserconfig]
  TileColor = "#2d89ef" # default windows 10 blue tile color

[[params.socialIcons]]
name = "github"
url = "https://github.com/hergerr"

[[params.socialIcons]]
name = "linkedin"
url = "https://www.linkedin.com/in/tymoteusz-frankiewicz"